import data from '../data/results.json';
import './style.css';
const ms=(s:number)=>(s*1000).toFixed(2);
const max=Math.max(...data.results.map(r=>r.max));
const source='https://github.com/AliHamzaAzam/SIMD_MPI_Optimization/blob/'+data.machine.sourceCommit+'/';
document.querySelector<HTMLDivElement>('#app')!.innerHTML=`
<header><a class="wordmark" href="#">OPTIMIZATION <span>/ NOTEBOOK</span></a><nav aria-label="Main"><a href="#results">Results</a><a href="#strategy">Strategy</a><a href="#method">Method</a></nav></header>
<main><section class="hero"><p class="eyebrow">COMPUTATIONAL OPTIMIZATION · EXPERIMENT 01</p><h1>Measure the work.<br><span>Understand the limits.</span></h1><p class="intro">A source-backed look at vector instructions and distributed sequence alignment, with a small, reproducible cloud benchmark.</p><div class="tags"><span>Serial baseline recorded</span><span>MPI measurement unavailable</span><span>SIMD measurement unavailable</span></div></section>
<section id="results"><div class="section-heading"><div><p class="eyebrow">01 / OBSERVATIONS</p><h2>What this machine measured</h2></div><span class="pill">${data.machine.architecture} · single process</span></div><div class="stats"><article><p>Input sets</p><strong>3</strong><small>4 synthetic proteins per set</small></article><article><p>Timed runs</p><strong>15</strong><small>5 samples per sequence length</small></article><article><p>Statistic</p><strong>Median</strong><small>Range shows observed variability</small></article></div>
<article class="chart"><div class="chart-title"><h3>Serial runtime by sequence length</h3><p>Whole-process wall time · milliseconds · lower is faster</p></div><div role="img" aria-label="Runtime bar chart. Exact values are in the table below.">${data.results.map(r=>`<div class="bar-row"><span>${r.length} residues</span><div class="track"><div class="bar" style="width:${r.seconds/max*100}%"></div></div><strong>${ms(r.seconds)} ms</strong></div>`).join('')}</div><p class="caption">Same source, compiler and cloud machine. Longer sequences change the workload; these bars are not speedup comparisons.</p><div class="table-wrap"><table><caption>Recorded runtime, five samples per dataset</caption><thead><tr><th scope="col">Residues / sequence</th><th scope="col">Median</th><th scope="col">Minimum</th><th scope="col">Maximum</th></tr></thead><tbody>${data.results.map(r=>`<tr><th scope="row">${r.length}</th><td>${ms(r.seconds)} ms</td><td>${ms(r.min)} ms</td><td>${ms(r.max)} ms</td></tr>`).join('')}</tbody></table></div></article>
<div class="two"><article class="note"><h3>Speedup: not measured</h3><p>MPI speedup needs the same MPI binary and input at one and multiple ranks on the same machine. The MPI compiler wrapper is present, but its development headers are absent. No parallel timing is reported.</p><code>S(p) = T(1) / T(p)</code></article><article class="note"><h3>Efficiency: not measured</h3><p>Efficiency divides speedup by the process count. With no compatible parallel runs, a percentage would be unsupported. Missing results are not zero performance.</p><code>E(p) = S(p) / p</code></article></div></section>
<section id="strategy"><p class="eyebrow">02 / IMPLEMENTATION</p><h2>Two ways to divide the work</h2><div class="two"><article class="note"><h3>SIMD: four lanes in one instruction</h3><p>The scalar code computes <code>C[i,j] = A[j,i] × B[i,j]</code>. This is transposed elementwise multiplication, not general matrix multiplication. NEON and Apple variants transpose A, then multiply four floats at once.</p><p>Apple and ARM headers prevent running this source on this Linux x86 machine. No SIMD claims are inferred from the serial alignment benchmark.</p><a href="${source}SIMD_Optimization/src/simd.cpp">Read SIMD source ↗</a></article><article class="note"><h3>MPI: distribute sequence transforms</h3><p>Rank 0 reads and partitions FASTA records. Workers compute padded FFTs and return them. Distance calculation, guide-tree construction and progressive alignment stay on rank 0, limiting scaling.</p><p>The serial implementation builds its alphabet mapping dynamically; MPI uses a fixed mapping. Treating them as an identical numerical baseline needs validation first.</p><a href="${source}MPI_Optimization/src/MPI.cpp">Read MPI source ↗</a></article></div>
<figure class="diagram"><div class="diagram-scroll" tabindex="0" role="region" aria-label="MPI strategy diagram, scroll horizontally to view all stages"><svg viewBox="0 0 800 230" role="img" aria-labelledby="flow-title flow-desc"><title id="flow-title">MPI work distribution</title><desc id="flow-desc">Rank zero reads sequences and sends partitions to worker FFTs. All transforms return to rank zero for distance calculation and progressive alignment.</desc><defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#7351b5"/></marker></defs><g fill="none" stroke="#7351b5" stroke-width="2" marker-end="url(#arrow)"><path d="M200 110 L285 60"/><path d="M200 110 L285 155"/><path d="M460 60 L545 110"/><path d="M460 155 L545 110"/></g><g fill="#f0eafb" stroke="#d9cdec"><rect x="15" y="70" width="185" height="80" rx="12"/><rect x="285" y="25" width="175" height="70" rx="12"/><rect x="285" y="120" width="175" height="70" rx="12"/><rect x="545" y="70" width="235" height="80" rx="12"/></g><g fill="#342449" text-anchor="middle" font-family="system-ui" font-size="16"><text x="108" y="102">Rank 0</text><text x="108" y="128">Read + partition</text><text x="372" y="54">Rank 0</text><text x="372" y="77">Local FFTs</text><text x="372" y="149">Worker ranks</text><text x="372" y="173">Local FFTs</text><text x="662" y="103">Rank 0</text><text x="662" y="128">Distances + alignment</text><text x="400" y="222" font-size="13">Only the sequence FFT stage is distributed.</text></g></svg></div><figcaption>Source-level strategy, not a measured MPI execution. On small screens, scroll horizontally to view all stages.</figcaption></figure></section>
<section id="method"><p class="eyebrow">03 / REPRODUCIBILITY</p><h2>The evidence behind the numbers</h2><div class="two"><article class="note"><h3>Measurement protocol</h3><p>${data.machine.scope}. One warm-up is excluded, then five runs per dataset. Unmodified C++ source receives only a FASTA path so progressive alignment is included.</p><p>Short runs include process launch overhead and cloud scheduling noise. This is a smoke benchmark, not a hardware ranking or a scaling study. Output checksums are checked within each dataset; this does not establish biological correctness.</p><p>Captured ${data.machine.capturedAt}. Raw standard output, standard error, timings, inputs and source hashes are retained in <code>web/raw/</code>.</p></article><article class="note"><h3>Execution record</h3><dl><dt>CPU</dt><dd>${data.machine.machine}</dd><dt>Operating system</dt><dd>${data.machine.os}</dd><dt>Compiler</dt><dd>${data.machine.compiler}</dd><dt>Compiler flags</dt><dd><code>${data.machine.flags}</code></dd><dt>Source revision</dt><dd><a href="${source}">${data.machine.sourceCommit.slice(0,12)}</a></dd></dl></article></div><div class="reproduce"><h3>Reproduce locally</h3><pre><code>cd web
npm ci
npm run data
npm test
npm run build
npm run dev</code></pre><p>With an existing C++17 compiler, <code>npm run benchmark</code> replaces the raw measurements and regenerates the data. See the repository README for prerequisites.</p></div></section></main><footer>AliHamzaAzam / SIMD_MPI_Optimization <span>Measured evidence. Explicit boundaries.</span></footer>`;
